#!/usr/bin/env python -c
# -*- coding utf-8 -*-

# This hook is run after every virtualenv is activated.


# auto switch path


PROJECT_DIR=$(python ~/.virtualenvs/postactivatePython.py)
cd $PROJECT_DIR
unset PROJECT_DIR
