#!/usr/bin/env python -c
# -*- coding utf-8 -*-

# This hook is run after every virtualenv is activated.


# auto switch path


proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
PROJECT_DIR=$(find '/home/richy/Projects' -maxdepth 2 -name $proj_name -type d)
cd $PROJECT_DIR
unset PROJECT_DIR
